[urc]
hostname=urc
image=quay.io/toolbx/ubuntu-toolbox:26.04
# Change to true if you have an nvidia GPU
nvidia=false
init-hooks='sh "test -f /opt/ros/lyrical/setup.${SHELL#/usr/bin/} ]] && source /opt/ros/lyrical/setup.${SHELL#/usr/bin/}"'

# To make your own distrobox setup you can also use the include flag
[test]
include=urc
# nvidia=true
home=/home/jade/docs/code/urc

[jetson]
hostname=jetson-dbox
image=quay.io/toolbx/ubuntu-toolbox:24.04
nvidia=true
